config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :home, only: [:index]

  resources :products do
    resources :reviews
  end

  get 'search' => 'products#search', as: 'search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :presence => true
  validates :price, :presence => true
  validates :country, :presence => true

  def country_name
    ISO3166::Country[country].name
  end

  scope :find_by_country, -> (country) { where(country: country) }
  scope :recent_products, -> { order(created_at: :desc).limit(3) }
  scope :most_reviewed, -> {(
    select("products.*, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :username, presence: true
  
  validates :content,
    presence: true,
    length: {
      in: 50..250
    }

  validates :rating,
    presence: true,
    inclusion: { 
      in: 1..5
    }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recent_products = Product.recent_products
    @most_reviewed = Product.most_reviewed
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order(:name).page params[:page]
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "The product has been updated."
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:notice] = "The product has been deleted."
    redirect_to root_path
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Your product has been saved."
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def search
    products = Product.find_by_country(params[:country])
    @products = products.page params[:page]
    render :index
  end

private
  def product_params
    params.require(:product).permit(:name, :price, :country)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "The review has been added."
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    product = Product.find(params[:product_id])
    Review.find(params[:id]).destroy
    flash[:notice] = "The review was sucessfully deleted."
    redirect_to product_path(product)
  end

private
  def review_params
    params.require(:review).permit(:username, :content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div id="home_index">

  <%= link_to "View All Products", products_path, class: "btn btn-default" %>
  <%= link_to "Add Product", new_product_path, class: "btn btn-default" %>

  <br><br>

  <%= form_tag(search_path, method: :get) do %>
    <div class="form-group">
      <label for="country">Search by Country</label>
      <%= country_select nil, :country, {selected: params[:country], priority_countries: ["US", "CA", "MX"]}, class: "form-control" %>
    </div>
    <%= submit_tag("Submit", class: "btn btn-default") %>
  <% end %>

  <h2>Most Recently Added Products:</h2>

  <div class="product">
    <% @recent_products.each do |product| %>
      <h3><%= link_to product.name, product_path(product) %></h3>
      <p>Created: <%= product.created_at.to_s(:long) %></p>
    <% end %>
  </div>

  <h2>Most Reviewed Product:</h2>

  <div class="product">
    <% @most_reviewed.each do |product| %>
      <h3><%= link_to product.name, product_path(product) %></h3>
      <p>Number of Reviews: <%= product.reviews.length %></p>
    <% end %>
  </div>
  
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<div id="header_partial">
  <div class="jumbotron">
    <div class="container">
      <h1><%= link_to "Super Store", root_path %></h1>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <% if notice || alert %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :price %>
  <%= f.text_field :price, class: "form-control" %>
  <%= f.label :country %>
  <%= f.country_select :country, { priority_countries: ["US", "CA", "MX"] }, { class: "form-control" } %>
  <br>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div id="product_index">

  <h3>There <%= @products.total_count == 1 ? "was" : "were" %> <%= pluralize @products.total_count, "result" %></h3>

  <% @products.each do |product| %>
    <h3><%= link_to product.name, product_path(product) %></h3>
  <% end %>
  
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div id="products_show">
  <%= link_to "Edit Product", edit_product_path(@product), class: "btn btn-default" %>
  <%= link_to "Delete Product", product_path(@product), data: {method: :delete}, class: "btn btn-danger" %>

  <h1><%= @product.name %></h1>
  <h4><%= @product.country_name %></h4>
  <h4><%= number_to_currency(@product.price) %></h4>
  
  <hr>

  <h2>Reviews <%= link_to "Add Review", new_product_review_path(@product), class: "btn btn-default" %></h2>
  <% @product.reviews.each do |review| %>
    <h4>
      <%= review.content %>
      <%= link_to product_review_path(@product, review), data: {method: :delete} do %>
        <span class="hidden">Delete Review</span>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>
    </h4>
    <p>by <%= review.username %></p>
    <p>Rating: <%= review.rating %></p>
  <% end %>

  <hr>


</div>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>
  <%= f.label :content %>
  <%= f.text_field :content, class: "form-control" %>
  <%= f.label :rating %>
  <%= f.text_field :rating, class: "form-control" %><br>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render "form" %>